# Generated by Django 4.1.2 on 2022-10-21 05:59

import GamesPlayApp.games_play_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_play_app', '0005_alter_profilemodel_age_alter_profilemodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='rating',
            field=models.FloatField(validators=[GamesPlayApp.games_play_app.validators.ValueInRangeValidator(0.1, 5.0)]),
        ),
    ]
