# Generated by Django 4.1.2 on 2022-10-21 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_play_app', '0006_alter_gamemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12)], verbose_name='Age'),
        ),
    ]
