# Generated by Django 4.1.2 on 2022-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_play_app', '0007_alter_profilemodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='category',
            field=models.CharField(choices=[('Action', 'action'), ('Adventure', 'adventure'), ('Puzzle', 'puzzle'), ('Strategy', 'strategy'), ('Sports', 'sports'), ('Board/Card', 'board/card Game'), ('Other', 'other')], max_length=15),
        ),
    ]
