# Generated by Django 4.1.2 on 2022-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_play_app', '0008_alter_gamemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Board/Card', 'Board/Card Game'), ('Other', 'Other')], max_length=15),
        ),
    ]
