# Generated by Django 4.1.1 on 2022-10-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0005_pet_type'),
    ]

    operations = [

    ]
