# Generated by Django 4.1.1 on 2022-10-11 15:47

from django.db import migrations, models
import petstagram.photos.validator


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_create_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./mediafiles/photos', validators=[petstagram.photos.validator.validate_file_size]),
        ),
    ]
