# Generated by Django 4.1.2 on 2022-10-22 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Pop Music', 'pop_music'), ('Jazz Music', 'jazz_music'), ('R&B Music', 'r&b_music'), ('Rock_Music', 'rock_music'), ('Country Music', 'country_music'), ('Dance Music', 'dance_music'), ('Hip Hop Music', 'hip_hop_music'), ('Other', 'other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15)])),
                ('email', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
