# Generated by Django 4.1.2 on 2022-10-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='genre',
            field=models.CharField(choices=[('pop_music', 'Pop Music'), ('jazz_music', 'Jazz Music'), ('r&b_music', 'R&B Music'), ('rock_music', 'Rock_Music'), ('country_music', 'Country Music'), ('dance_music', 'Dance Music'), ('hip_hop_music', 'Hip Hop Music'), ('other', 'Other')], max_length=30),
        ),
    ]
