# Generated by Django 4.1.1 on 2022-10-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [

    ]
