# Generated by Django 4.1.2 on 2022-10-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
