# Generated by Django 4.1.2 on 2022-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_alter_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(verbose_name='Link to Profile Image'),
        ),
    ]
